# Generated by Django 6.0.3 on 2026-03-08 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('organizer', 'Organizer'), ('attendee', 'Attendee')], default='attendee', max_length=20),
        ),
    ]
