# Generated by Django 6.0.3 on 2026-04-28 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='total_tickets',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Capacity'),
        ),
    ]
