# Generated by Django 6.0.3 on 2026-04-28 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_total_tickets'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='price_details',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Price note'),
        ),
    ]
