# Generated by Django 6.0.3 on 2026-04-28 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_price_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='payment_details',
            field=models.CharField(blank=True, help_text='Enter a till number or phone number', max_length=100, null=True, verbose_name='Payment details'),
        ),
        migrations.AddField(
            model_name='event',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('till', 'Till Number'), ('phone', 'Phone Number')], max_length=20, null=True, verbose_name='Payment method'),
        ),
    ]
